# Dependencies
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Jordan Robinson
tagline:          'A Blog'
description:      ''
url:              http://blog.jordanrobinson.co.uk
baseurl:          /

author:
  name:           'Jordan Robinson'
  url:            http://jordanrobinson.co.uk

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jordanrobinson/blog
